server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://localhost:27017
  database: masterdata

batch_worker:
  batch_size: 5
  timeout: 5000
  limit_retry: 3

amq:
  addr: localhost:61613
  username: admin
  password: admin
  destination_name: test
  subscription_name: test