server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://localhost:27017
  database: masterdata

batch_worker:
  batch_size: 5
  timeout: 5000
  limit_retry: 3

receiver:
  region: abc
  access_key_id: abc
  secret_access_key: abc
  queue_name: abc

sender:
  region: abc
  access_key_id: abc
  secret_access_key: abc
  queue_name: abc
