server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message


dynamodb:
  access_key_id: IDdemo
  secret_access_key: KEYdemo
  region: us-west-2
  token:


batch_worker:
  batch_size: 100
  timeout: 5000
  limit_retry: 3

reader:
  kafka:
    brokers: tricycle-01.srvs.cloudkafka.com:9094
    client:
      username: username-demo
      password: pwdemo
    group_id: my-group
    topic: demo-default
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

writer:
  brokers:
    - tricycle-01.srvs.cloudkafka.com:9094
    - tricycle-02.srvs.cloudkafka.com:9094
    - tricycle-03.srvs.cloudkafka.com:9094
  client:
    username: username-demo
    password: pwdemo
  topic: demo-default
