server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://localhost:27017
  database: masterdata

batch_worker:
  batch_size: 100
  timeout: 5000
  limit_retry: 3


subscriber:
  nats:
    subject: ah1t9hk0-default
    header: true
    connection:
      url: nats://127.0.0.1:4222
  retry:
    retry_count_name: retry
    limit_retry: 3
    goroutines: false

publisher:
  subject: ah1t9hk0-default
  header: true
  connection:
    url: nats://127.0.0.1:4222