server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://localhost:27017
  database: masterdata

batch_worker:
  batch_size: 3
  timeout: 5000
  limit_retry: 3

consumer:
  url: amqp://guest:guest@localhost:5672/
  exchange_name: test
  exchange_kind: fanout
  auto_delete: false

publisher:
  url: amqp://guest:guest@localhost:5672/
  exchange_name: test
  exchange_kind: fanout
  auto_delete: false
  content_type: text/plain
